"""Add simulated_actions table"""
from alembic import op
import sqlalchemy as sa

revision = 'c4825496c818'
down_revision = 'b66cca45d59c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulated_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('opportunity_id', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('estimated_revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expected_conversion', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('simulation_result', sa.String(), nullable=True),
    sa.Column('feedback', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('actionstatus'), 'actions', type_='check')
    op.drop_constraint(op.f('customersegment'), 'customers', type_='check')
    op.drop_constraint(op.f('opportunitystatus'), 'opportunities', type_='check')
    op.drop_constraint(op.f('orderstatus'), 'orders', type_='check')
    op.drop_constraint(op.f('paymentstatus'), 'payments', type_='check')
    op.drop_constraint(op.f('subscriptionstatus'), 'subscriptions', type_='check')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_check_constraint(op.f('subscriptionstatus'), 'subscriptions', "status IN ('ACTIVE', 'PAST_DUE', 'CANCELLED')")
    op.create_check_constraint(op.f('paymentstatus'), 'payments', "status IN ('SUCCEEDED', 'FAILED')")
    op.create_check_constraint(op.f('orderstatus'), 'orders', "status IN ('COMPLETED', 'PENDING', 'ABANDONED')")
    op.create_check_constraint(op.f('opportunitystatus'), 'opportunities', "status IN ('DETECTED', 'DISMISSED', 'ACTIONED')")
    op.create_check_constraint(op.f('customersegment'), 'customers', "segment IN ('NEW', 'REGULAR', 'HIGH_VALUE', 'AT_RISK', 'INACTIVE')")
    op.create_check_constraint(op.f('actionstatus'), 'actions', "status IN ('PROPOSED', 'SIMULATED', 'COMPLETED')")
    op.drop_table('simulated_actions')
    # ### end Alembic commands ###
